#!/usr/bin/env bash

set -e

echo "install nvim-config"
cd ./lua-nvim && ./install "$@" && cd ..
echo "done: install nvim-config"

echo "install vimrc"
[ -f ../os ] && source ../os

cp -r ./vim/.vim/ ~/

case "$OS" in
"MAC")
	echo "found as MacOS, cp .vim rc files.."
	cp ./vim/.vimrc ~
	;;
"UBUNTU")
	echo "found as ubuntu. cp ubuntu rc files.."
	cp ./vim/.vimrc-ubuntu ~/.vimrc
	;;
**)
	echo "unknown os"
	;;
esac

source ./func

opts "$@"
if [ $PACKAGE = true ]; then
	PKGM=$(getpkgm)
	echo "pkgm $PKGM"
	install exuberant-ctags "$PKGM"
fi

echo "done:install vimrc"
