#!/usr/bin/env bash

set -e

source ../../os
source ../../func
echo "the os is $OS"

if [ ! -e "$HOME/.config/nvim" ]; then
	echo "no nvim"
	exit 0
fi

INSTALL_PATH=$HOME/.config/nvim/lua/custom
mkdir -p $INSTALL_PATH

main() {
	cp -r ./* "$INSTALL_PATH"

  # node
  install nodejs "$PKGM"
  install npm "$PKGM"

  # pnpm
  PNPM=$(which pnpm)

  if [ -z "$PNPM" ]; then
    echo "install pnpm"
    curl -fsSL https://get.pnpm.io/install.sh | sh -
    #npm --global add pnpm
  fi

}

getpkgm() {
	case $OS in
	'MAC') echo 'brew' ;;
	'UBUNTU') echo 'apt' ;;
	*) 'unknown os' ;;
	esac
}

install() {
	case $2 in
	'apt')
		if ! dpkg -s "$1" >/dev/null 2>&1; then
			echo -e "install.. \e[1;32m $1 \e[0m"
			sudo apt-get install "$1"
		fi
		;;
	'brew')
		INSTALLED=$(brew list "$1")
		if [ -z "$INSTALLED" ]; then
			echo -e "install.. \e[1;32m $1 \e[0m"
			brew install "$1"
		fi
		;;
	'pnpm')
		INSTALLED=$(pnpm list -g "$1")
		if [ -z "$INSTALLED" ]; then
			echo -e "install.. \e[1;32m $1 \e[0m"
			pnpm i -g "$1"
		fi
		;;
	*)
		echo "unknown command: $2"
		;;
	esac
}

main "$@"
