#!/usr/bin/env bash

set -e

source ../../os
source ../../func
echo "the os is $OS"

if [ ! -e "$HOME/.config/nvim" ]; then
  echo "no nvim"
  exit 0
fi

INSTALL_PATH=$HOME/.config/nvim/lua/custom
mkdir -p "$INSTALL_PATH"

main() {
  opts "$@"
  cp -r ./* "$INSTALL_PATH"

  if [ $PACKAGE = true ]; then
    PKGM=$(getpkgm)
    echo "install package for nvim configuration"
    # node
    install nodejs "$PKGM"
    install npm "$PKGM"

    # pnpm
    PNPM=$(which pnpm)

    if [ -z "$PNPM" ]; then
      echo "install pnpm"
      curl -fsSL https://get.pnpm.io/install.sh | sh -
      #npm --global add pnpm
    fi

    # plugin
    install libmagickwand-dev "$PKGM"
    pnpm add -g @mermaid-js/mermaid-cli
  fi
}

main "$@"
