#!/usr/bin/env bash

source ./os
source ./func
echo "the os is $OS"

if [ ! -f $HOME/.config/nvim ]; then
  echo "no nvim"
  exit 0
fi

INSTALL_PATH=$HOME/.config/nvim/lua/custom

main() {
	cp -r ./* "$INSTALL_PATH"
	opts "$@"
	if [ $PACKAGE = true ]; then
		PKGM=$(getpkgm)
		echo "install packages. pkgm $PKGM"

		# pnpm
		PNPM=$(which pnpm)
		if [ -z "$PNPM" ]; then
			echo "install pnpm"
			curl -fsSL https://get.pnpm.io/install.sh | sh -
		fi

		## langs
		install go "$PKGM"

		## telescope
		install ripgrep "$PKGM"

		## lsp
		install bash-language-server "$PKGM"
		install @prisma/language-server pnpm

		## formatting
		install prettier "$PKGM"
		install stylua "$PKGM"
		install shfmt "$PKGM"
		install black "$PKGM"

		## etc
		install code-minimap "$PKGM"
	fi

	[ $CONF = true ] && FILEPATH="$INSTALL_PATH/post-init.lua" || FILEPATH=$FILE

	if [ ! -z "$FILEPATH" ]; then
		echo "post process for init-lua using ($FILEPATH)"
		# sed -i '' -E 's/-- autogen {{{\_.*-- autogen }}}//' ./init.lua
		#     RPL=$(tr '\n' '\f' < init.lua |
		#       sed -e 's/-- autogen {{{.*\f*.*-- autogen }}}//' | tr '\f' '\n')
		#     # remove prev data
		#     cat <<EOF > "$INSTALL_PATH"/init.lua
		# $RPL
		# EOF
		cat "$FILEPATH" >>"$INSTALL_PATH"/init.lua
	fi
}

getpkgm() {
	case $OS in
	'MAC') echo 'brew' ;;
	'UBUNTU') echo 'apt' ;;
	*) 'unknown os' ;;
	esac
}

install() {
	case $2 in
	'apt')
		INSTALLED=$(apt list "$1")
		if [ -z "$INSTALLED" ]; then
			apt install "$1"
		fi
		;;
	'brew')
		INSTALLED=$(brew list "$1")
		if [ -z "$INSTALLED" ]; then
			brew install "$1"
		fi
		;;
	'pnpm')
		INSTALLED=$(pnpm list -g "$1")
		if [ -z "$INSTALLED" ]; then
			pnpm i -g "$1"
		fi
		;;
	*)
		echo "unknown command: $2"
		;;
	esac
}

main "$@"
