#!/usr/bin/env bash

source ./os
source ./func
echo "the os is $OS"

if [ ! -e "$HOME/.config/nvim" ]; then
	echo "no nvim"
	exit 0
fi

mkdir -p "$HOME/.config/nvim/lua/custom"
INSTALL_PATH=$HOME/.config/nvim/lua/custom

main() {
	cp -r ./* "$INSTALL_PATH"
	opts "$@"
	if [ $PACKAGE = true ]; then
		PKGM=$(getpkgm)
		echo "install packages. pkgm $PKGM"

    # node
    install nodejs "$PKGM"
    install npm "$PKGM"

		# pnpm
		PNPM=$(which pnpm)
		if [ -z "$PNPM" ]; then
			echo "install pnpm"
			curl -fsSL https://get.pnpm.io/install.sh | sh -
			#npm --global add pnpm
		fi

		## langs
		install go "$PKGM"
		install ccls "$PKGM"
    install g++ "$PKGM"

		## telescope
		install ripgrep "$PKGM"

		## etc
		if [ $OS != "UBUNTU" ]; then
			install code-minimap "$PKGM"
    elif [ -z "$(which code-minimap)" ]; then
			wget https://github.com/wfxr/code-minimap/releases/download/v0.6.4/code-minimap-v0.6.4-aarch64-unknown-linux-gnu.tar.gz
			tar -xvf ./code-minimap-v0.6.4-aarch64-unknown-linux-gnu.tar.gz
			sudo mkdir -p /opt/bin
			sudo mv ./code-minimap-v0.6.4-aarch64-unknown-linux-gnu/code-minimap /opt/bin
			rm -rf ./code-minimap-v0.6.4-aarch64-unknown-linux-gnu
			rm -rf ./code-minimap-v0.6.4-aarch64-unknown-linux-gnu.tar.gz
		fi

		install spell "$PKGM"
	fi

	[ $CONF = true ] && FILEPATH="$INSTALL_PATH/post-init.lua" || FILEPATH=$FILE

	if [ -n "$FILEPATH" ]; then
		echo "post process for init-lua using ($FILEPATH)"
		# sed -i '' -E 's/-- autogen {{{\_.*-- autogen }}}//' ./init.lua
		#     RPL=$(tr '\n' '\f' < init.lua |
		#       sed -e 's/-- autogen {{{.*\f*.*-- autogen }}}//' | tr '\f' '\n')
		#     # remove prev data
		#     cat <<EOF > "$INSTALL_PATH"/init.lua
		# $RPL
		# EOF
		cat "$FILEPATH" >>"$INSTALL_PATH"/init.lua
	fi
}

getpkgm() {
	case $OS in
	'MAC') echo 'brew' ;;
	'UBUNTU') echo 'apt' ;;
	*) 'unknown os' ;;
	esac
}

install() {
	case $2 in
	'apt')
		if ! dpkg -s "$1" >/dev/null 2>&1; then
			sudo apt-get install "$1"
		fi
		;;
	'brew')
		INSTALLED=$(brew list "$1")
		if [ -z "$INSTALLED" ]; then
			brew install "$1"
		fi
		;;
	'pnpm')
		INSTALLED=$(pnpm list -g "$1")
		if [ -z "$INSTALLED" ]; then
			pnpm i -g "$1"
		fi
		;;
	*)
		echo "unknown command: $2"
		;;
	esac
}

main "$@"
