#!/usr/bin/env bash

echo "install kotlin environment"

source ./os
source ./func
echo "the os is $OS"

main() {

	PKGM=$(getpkgm)

	install kotlin "$PKGM"
	install gradle "$PKGM"

	# if [ $OS = "MAC" ]; then
	# 	wget https://download.java.net/java/GA/jdk19.0.1/afdd2e245b014143b62ccb916125e3ce/10/GPL/openjdk-19.0.1_macos-aarch64_bin.tar.gz
	# 	tar -xvf ./openjdk-19.0.1_macos-aarch64_bin
	# 	mkdir -p /Library/Java/JavaVirtualMachines
	# 	mv ./openjdk-19.0.1 /Library/Java/JavaVirtualMachines
	#
	# elif [ $OS = "UBUNTU" ]; then
	# 	install openjdk-19.0.1 "$PKGM"
	# fi
}

getpkgm() {
	case $OS in
	'MAC') echo 'brew' ;;
	'UBUNTU') echo 'apt' ;;
	*) 'unknown os' ;;
	esac
}

install() {
	case $2 in
	'apt')
		if ! dpkg -s "$1" >/dev/null 2>&1; then
			sudo apt-get install "$1"
		fi
		;;
	'brew')
		INSTALLED=$(brew list "$1")
		if [ -z "$INSTALLED" ]; then
			brew install "$1"
		fi
		;;
	'pnpm')
		INSTALLED=$(pnpm list -g "$1")
		if [ -z "$INSTALLED" ]; then
			pnpm i -g "$1"
		fi
		;;
	*)
		echo "unknown command: $2"
		;;
	esac
}

main "$@"
